[project]
name = "kcn"
version = "0.1.0"
description = "App local-first de nutrición y conteo de calorías"
requires-python = ">=3.10"
dependencies = []

[project.optional-dependencies]
dev = ["pytest>=8.0"]
# Estas las instalaremos cuando lleguemos a la UI y la base de datos:
ui = ["flet>=0.24", "sqlmodel>=0.0.22", "httpx>=0.27"]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]